spring:
  output:
    ansi:
      enabled: always

  # 정적 소스 cache 미적용
  resources:
    static-locations: classpath:/static/
    cache-period: 0

  # thymeleaf cache 미적용
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false

  # mysql 연결
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.47.75.102:3306/dbsanghobim?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: sanghobim
    password: sangho20##
    #mapper-locations: classpath:/mapper/**/*.xml

 # mybatis
    mybatis:
#      config= mybatis-config.xml
      type-aliases-package: com.tour.FootStamp.model
      mapper-locations: mybatis/mapper/**/*.xml

    mybatis.config: mybatis-config.xml


    #server:
    #  ssl:
    #    enabled: true
    #    key-store-type: PKCS12
    #    key-store: keystore.p12 #classpath:/
    #    key-store-password: 1q2w3e4r
    #    key-password: 1q2w3e4r
    #port: 8443