spring:
  output:
    ansi:
      enabled: always

  # 정적 소스 cache 미적용
  resources:
    static-locations: classpath:/static/
    cache-period: 0

  # thymeleaf cache 미적용
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
